# Generated by Django 6.1 on 2026-09-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_branch_manager_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="special_request",
            field=models.TextField(blank=True, default=""),
        ),
    ]
