# Generated by Django 6.1 on 2026-09-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_booking_special_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('BOOKING', 'Booking'), ('PREORDER', 'Food pre-order')], max_length=20)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_status_changes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='restaurants.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_status_history', to='restaurants.branch')),
                ('preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='restaurants.foodpreorder')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_status_history', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'created_at'], name='restaurants_target__ce8a19_idx'), models.Index(fields=['restaurant', 'created_at'], name='restaurants_restaur_ee2535_idx'), models.Index(fields=['branch', 'created_at'], name='restaurants_branch__f8c9d1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('preorder__isnull', True), ('target_type', 'BOOKING')), models.Q(('booking__isnull', True), ('preorder__isnull', False), ('target_type', 'PREORDER')), _connector='OR'), name='history_target_matches_type'), models.CheckConstraint(condition=models.Q(('old_status', models.F('new_status')), _negated=True), name='history_records_real_change')],
            },
        ),
    ]
